### ISSUE TITLE
Current state of the project?

### ISSUE THREAD

**Issue by oyeanuj** [slang-legacy/hemingway#4]
Hey @slang800! I came across this project while trying to find JS solutions around proofreading, and was excited to find this.

I'm curious if this is still in active development in some other form, or is demo-ed at some link? Or would you recommend a different library if needing to build something similar?

Thank you for open-sourcing this!

**Comment by notslang** [comment]
This was a repo for reverse-engineering the web version of http://www.hemingwayapp.com/ ... Haven't kept up with it though, and the official app hasn't been released as free software.

**Comment by notslang** [comment]
Oh, also: take a look at https://github.com/btford/write-good and https://github.com/amperser/proselint/

**Comment by oyeanuj** [comment]
> This was a repo for reverse-engineering the web version of http://www.hemingwayapp.com/ ... 
Ah, that's how I ended up here as well :)

Thanks for those links, I'll try to see how I can maybe integrate those tools. Proselint seems like a python only tool unfortunately :(

I was curious though - if you also managed to reverse-engineer the readability level concept from the Hemingway app?

**Comment by notslang** [comment]
> I was curious though - if you also managed to reverse-engineer the readability level concept from the Hemingway app?

No, I was just interested in the structure of the demo and what word-lists they were using. However, [Flesch–Kincaid readability / grade level scores](https://en.wikipedia.org/wiki/Flesch%E2%80%93Kincaid_readability_tests) are pretty well-defined and easy to code.
